// data.js - Expanded Salesforce-formatted seating data with all days and correct event types

const SALESFORCE_DATA = [
  // Day 1 - Friday bookings

  // Connected seats: Calgary Co-op - 4 adjacent seats in Row C (41-44) - Day 1
  {
    Id: "00kAs00000030041ZZAQ",
    Opportunity_Account_Name: "Calgary Co-op",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "41.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-CalgaryCoOp-001",
  },
  {
    Id: "00kAs00000030042ZZAQ",
    Opportunity_Account_Name: "Calgary Co-op",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "42.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-CalgaryCoOp-001",
  },
  {
    Id: "00kAs00000030043ZZAQ",
    Opportunity_Account_Name: "Calgary Co-op",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "43.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-CalgaryCoOp-001",
  },
  {
    Id: "00kAs00000030044ZZAQ",
    Opportunity_Account_Name: "Calgary Co-op",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "44.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-CalgaryCoOp-001",
  },

  // Connected seats: TransCanada Pipeline - Row D seats 35-39 - Day 1
  {
    Id: "00kAs00000060035ZZAQ",
    Opportunity_Account_Name: "TransCanada Pipeline",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "35.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TransCanada-001",
  },
  {
    Id: "00kAs00000060036ZZAQ",
    Opportunity_Account_Name: "TransCanada Pipeline",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "36.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TransCanada-001",
  },
  {
    Id: "00kAs00000060037ZZAQ",
    Opportunity_Account_Name: "TransCanada Pipeline",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "37.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TransCanada-001",
  },
  {
    Id: "00kAs00000060038ZZAQ",
    Opportunity_Account_Name: "TransCanada Pipeline",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "38.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TransCanada-001",
  },
  {
    Id: "00kAs00000060039ZZAQ",
    Opportunity_Account_Name: "TransCanada Pipeline",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "39.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TransCanada-001",
  },

  // Connected seats: Shaw Communications - 3 adjacent seats in Row B (38-40) - Day 1
  {
    Id: "00kAs00000080038ZZAQ",
    Opportunity_Account_Name: "Shaw Communications",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "38.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Shaw-001",
  },
  {
    Id: "00kAs00000080039ZZAQ",
    Opportunity_Account_Name: "Shaw Communications",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "39.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Shaw-001",
  },
  {
    Id: "00kAs00000080040ZZAQ",
    Opportunity_Account_Name: "Shaw Communications",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "40.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Shaw-001",
  },

  // Day 2 - Saturday bookings

  // Connected seats: ATCO Gas - 5 adjacent seats in Row B (45-49) - Day 2
  {
    Id: "00kAs00000040045ZZAQ",
    Opportunity_Account_Name: "ATCO Gas",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "45.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-ATCO-001",
  },
  {
    Id: "00kAs00000040046ZZAQ",
    Opportunity_Account_Name: "ATCO Gas",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "46.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-ATCO-001",
  },
  {
    Id: "00kAs00000040047ZZAQ",
    Opportunity_Account_Name: "ATCO Gas",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "47.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-ATCO-001",
  },
  {
    Id: "00kAs00000040048ZZAQ",
    Opportunity_Account_Name: "ATCO Gas",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "48.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-ATCO-001",
  },
  {
    Id: "00kAs00000040049ZZAQ",
    Opportunity_Account_Name: "ATCO Gas",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "49.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-ATCO-001",
  },

  // Connected seats: WestJet Airlines - Row E seats 30-34 - Day 2
  {
    Id: "00kAs00000070030ZZAQ",
    Opportunity_Account_Name: "WestJet Airlines",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "30.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-WestJet-001",
  },
  {
    Id: "00kAs00000070031ZZAQ",
    Opportunity_Account_Name: "WestJet Airlines",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "31.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-WestJet-001",
  },
  {
    Id: "00kAs00000070032ZZAQ",
    Opportunity_Account_Name: "WestJet Airlines",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "32.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-WestJet-001",
  },
  {
    Id: "00kAs00000070033ZZAQ",
    Opportunity_Account_Name: "WestJet Airlines",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "33.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-WestJet-001",
  },
  {
    Id: "00kAs00000070034ZZAQ",
    Opportunity_Account_Name: "WestJet Airlines",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "34.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-WestJet-001",
  },

  // Day 3 - Sunday bookings

  // Connected seats: Suncor Energy - 6 adjacent seats in Row A (38-43) - Day 3
  {
    Id: "00kAs00000050038ZZAQ",
    Opportunity_Account_Name: "Suncor Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "38.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Suncor-001",
  },
  {
    Id: "00kAs00000050039ZZAQ",
    Opportunity_Account_Name: "Suncor Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "39.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Suncor-001",
  },
  {
    Id: "00kAs00000050040ZZAQ",
    Opportunity_Account_Name: "Suncor Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "40.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Suncor-001",
  },
  {
    Id: "00kAs00000050041ZZAQ",
    Opportunity_Account_Name: "Suncor Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "41.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Suncor-001",
  },
  {
    Id: "00kAs00000050042ZZAQ",
    Opportunity_Account_Name: "Suncor Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "42.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Suncor-001",
  },
  {
    Id: "00kAs00000050043ZZAQ",
    Opportunity_Account_Name: "Suncor Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "43.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Suncor-001",
  },

  // Day 4 - Monday bookings

  // BMO Financial Group - 4 adjacent seats in Row C (35-38) - Day 4
  {
    Id: "00kAs00000090035ZZAQ",
    Opportunity_Account_Name: "BMO Financial Group",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "35.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 4 - Monday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-BMO-001",
  },
  {
    Id: "00kAs00000090036ZZAQ",
    Opportunity_Account_Name: "BMO Financial Group",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "36.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 4 - Monday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-BMO-001",
  },
  {
    Id: "00kAs00000090037ZZAQ",
    Opportunity_Account_Name: "BMO Financial Group",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "37.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 4 - Monday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-BMO-001",
  },
  {
    Id: "00kAs00000090038ZZAQ",
    Opportunity_Account_Name: "BMO Financial Group",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "38.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 4 - Monday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-BMO-001",
  },

  // Day 5 - Tuesday bookings

  // Connected seats: Deloitte - 3 adjacent seats in Row D (42-44) - Day 5
  {
    Id: "00kAs00000110042ZZAQ",
    Opportunity_Account_Name: "Deloitte",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "42.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Deloitte-001",
  },
  {
    Id: "00kAs00000110043ZZAQ",
    Opportunity_Account_Name: "Deloitte",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "43.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Deloitte-001",
  },
  {
    Id: "00kAs00000110044ZZAQ",
    Opportunity_Account_Name: "Deloitte",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "44.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Deloitte-001",
  },

  // Connected seats: RBC Royal Bank - 5 adjacent seats in Row B (30-34) - Day 5
  {
    Id: "00kAs00000120030ZZAQ",
    Opportunity_Account_Name: "RBC Royal Bank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "30.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-RBC-001",
  },
  {
    Id: "00kAs00000120031ZZAQ",
    Opportunity_Account_Name: "RBC Royal Bank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "31.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-RBC-001",
  },
  {
    Id: "00kAs00000120032ZZAQ",
    Opportunity_Account_Name: "RBC Royal Bank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "32.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-RBC-001",
  },
  {
    Id: "00kAs00000120033ZZAQ",
    Opportunity_Account_Name: "RBC Royal Bank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "33.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-RBC-001",
  },
  {
    Id: "00kAs00000120034ZZAQ",
    Opportunity_Account_Name: "RBC Royal Bank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "34.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-RBC-001",
  },

  // Day 6 - Wednesday bookings

  // Connected seats: Husky Energy - 4 adjacent seats in Row A (46-49) - Day 6
  {
    Id: "00kAs00000130046ZZAQ",
    Opportunity_Account_Name: "Husky Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "46.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 6 - Wednesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Husky-001",
  },
  {
    Id: "00kAs00000130047ZZAQ",
    Opportunity_Account_Name: "Husky Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "47.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 6 - Wednesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Husky-001",
  },
  {
    Id: "00kAs00000130048ZZAQ",
    Opportunity_Account_Name: "Husky Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "48.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 6 - Wednesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Husky-001",
  },
  {
    Id: "00kAs00000130049ZZAQ",
    Opportunity_Account_Name: "Husky Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "49.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 6 - Wednesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Husky-001",
  },

  // Day 7 - Thursday bookings

  // Connected seats: CP Rail - 6 adjacent seats in Row C (45-50) - Day 7
  {
    Id: "00kAs00000150045ZZAQ",
    Opportunity_Account_Name: "CP Rail",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "45.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CPRail-001",
  },
  {
    Id: "00kAs00000150046ZZAQ",
    Opportunity_Account_Name: "CP Rail",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "46.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CPRail-001",
  },
  {
    Id: "00kAs00000150047ZZAQ",
    Opportunity_Account_Name: "CP Rail",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "47.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CPRail-001",
  },
  {
    Id: "00kAs00000150048ZZAQ",
    Opportunity_Account_Name: "CP Rail",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "48.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CPRail-001",
  },
  {
    Id: "00kAs00000150049ZZAQ",
    Opportunity_Account_Name: "CP Rail",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "49.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CPRail-001",
  },
  {
    Id: "00kAs00000150050ZZAQ",
    Opportunity_Account_Name: "CP Rail",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "50.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CPRail-001",
  },

  // Day 8 - Friday bookings

  // Connected seats: TD Bank - 5 adjacent seats in Row E (40-44) - Day 8
  {
    Id: "00kAs00000170040ZZAQ",
    Opportunity_Account_Name: "TD Bank",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "40.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TDBank-001",
  },
  {
    Id: "00kAs00000170041ZZAQ",
    Opportunity_Account_Name: "TD Bank",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "41.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TDBank-001",
  },
  {
    Id: "00kAs00000170042ZZAQ",
    Opportunity_Account_Name: "TD Bank",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "42.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TDBank-001",
  },
  {
    Id: "00kAs00000170043ZZAQ",
    Opportunity_Account_Name: "TD Bank",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "43.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TDBank-001",
  },
  {
    Id: "00kAs00000170044ZZAQ",
    Opportunity_Account_Name: "TD Bank",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "44.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TDBank-001",
  },

  // Connected seats: CIBC - 3 adjacent seats in Row D (30-32) - Day 8 Evening Show
  {
    Id: "00kAs00000180030ZZAQ",
    Opportunity_Account_Name: "CIBC",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "30.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CIBC-001",
  },
  {
    Id: "00kAs00000180031ZZAQ",
    Opportunity_Account_Name: "CIBC",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "31.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CIBC-001",
  },
  {
    Id: "00kAs00000180032ZZAQ",
    Opportunity_Account_Name: "CIBC",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "32.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CIBC-001",
  },

  // Day 9 - Saturday bookings

  // Connected seats: Scotiabank - 5 adjacent seats in Row B (35-39) - Day 9
  {
    Id: "00kAs00000190035ZZAQ",
    Opportunity_Account_Name: "Scotiabank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "35.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Scotiabank-001",
  },
  {
    Id: "00kAs00000190036ZZAQ",
    Opportunity_Account_Name: "Scotiabank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "36.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Scotiabank-001",
  },
  {
    Id: "00kAs00000190037ZZAQ",
    Opportunity_Account_Name: "Scotiabank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "37.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Scotiabank-001",
  },
  {
    Id: "00kAs00000190038ZZAQ",
    Opportunity_Account_Name: "Scotiabank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "38.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Scotiabank-001",
  },
  {
    Id: "00kAs00000190039ZZAQ",
    Opportunity_Account_Name: "Scotiabank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "39.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Scotiabank-001",
  },

  // Connected seats: Enbridge - 4 adjacent seats in Row A (34-37) - Day 9 Rodeo
  {
    Id: "00kAs00000200034ZZAQ",
    Opportunity_Account_Name: "Enbridge",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "34.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Enbridge-001",
  },
  {
    Id: "00kAs00000200035ZZAQ",
    Opportunity_Account_Name: "Enbridge",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "35.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Enbridge-001",
  },
  {
    Id: "00kAs00000200036ZZAQ",
    Opportunity_Account_Name: "Enbridge",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "36.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Enbridge-001",
  },
  {
    Id: "00kAs00000200037ZZAQ",
    Opportunity_Account_Name: "Enbridge",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "37.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Enbridge-001",
  },

  // Day 10 - Sunday bookings

  // Connected seats: Cenovus Energy - 6 adjacent seats in Row C (30-35) - Day 10
  {
    Id: "00kAs00000210030ZZAQ",
    Opportunity_Account_Name: "Cenovus Energy",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "30.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Cenovus-001",
  },
  {
    Id: "00kAs00000210031ZZAQ",
    Opportunity_Account_Name: "Cenovus Energy",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "31.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Cenovus-001",
  },
  {
    Id: "00kAs00000210032ZZAQ",
    Opportunity_Account_Name: "Cenovus Energy",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "32.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Cenovus-001",
  },
  {
    Id: "00kAs00000210033ZZAQ",
    Opportunity_Account_Name: "Cenovus Energy",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "33.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Cenovus-001",
  },
  {
    Id: "00kAs00000210034ZZAQ",
    Opportunity_Account_Name: "Cenovus Energy",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "34.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Cenovus-001",
  },
  {
    Id: "00kAs00000210035ZZAQ",
    Opportunity_Account_Name: "Cenovus Energy",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "35.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Cenovus-001",
  },

  // Connected seats: Telus - 4 adjacent seats in Row D (46-49) - Day 10 Evening Show
  {
    Id: "00kAs00000220046ZZAQ",
    Opportunity_Account_Name: "Telus",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "46.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Telus-001",
  },
  {
    Id: "00kAs00000220047ZZAQ",
    Opportunity_Account_Name: "Telus",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "47.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Telus-001",
  },
  {
    Id: "00kAs00000220048ZZAQ",
    Opportunity_Account_Name: "Telus",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "48.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Telus-001",
  },
  {
    Id: "00kAs00000220049ZZAQ",
    Opportunity_Account_Name: "Telus",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "49.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Telus-001",
  },
];
