// data.js - Expanded Salesforce-formatted seating data with all days and correct event types

const SALESFORCE_DATA = [
  // ===== BOOKING THAT SPANS ACROSS STAIRWAY =====
  // Acme Corporation - 7 seats spanning across stairway in Row D (64-70) - Day 1 (spans stairway between 65-68)
  {
    Id: "00kAs00000400064ZZAQ",
    Opportunity_Account_Name: "Acme Corporation",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "64.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Acme-001",
  },
  {
    Id: "00kAs00000400065ZZAQ",
    Opportunity_Account_Name: "Acme Corporation",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "65.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Acme-001",
  },
  // Stairway between 65-68
  {
    Id: "00kAs00000400068ZZAQ",
    Opportunity_Account_Name: "Acme Corporation",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "68.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Acme-001",
  },
  {
    Id: "00kAs00000400069ZZAQ",
    Opportunity_Account_Name: "Acme Corporation",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "69.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Acme-001",
  },
  {
    Id: "00kAs00000400070ZZAQ",
    Opportunity_Account_Name: "Acme Corporation",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "70.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Acme-001",
  },
  // ===== BOOKINGS THAT SPAN ACROSS PILLARS =====

  // Alberta Energy - 6 seats spanning across pillar in Row E (38-43) - Day 3 (spans pillar at E40-41)
  {
    Id: "00kAs00000300038ZZAQ",
    Opportunity_Account_Name: "Alberta Energy",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "38.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-AlbertaEnergy-001",
  },
  {
    Id: "00kAs00000300039ZZAQ",
    Opportunity_Account_Name: "Alberta Energy",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "39.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-AlbertaEnergy-001",
  },
  // Pillar at E40-41
  {
    Id: "00kAs00000300042ZZAQ",
    Opportunity_Account_Name: "Alberta Energy",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "42.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-AlbertaEnergy-001",
  },
  {
    Id: "00kAs00000300043ZZAQ",
    Opportunity_Account_Name: "Alberta Energy",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "43.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-AlbertaEnergy-001",
  },

  // PCL Construction - 6 seats spanning across pillar in Row E (54-59) - Day 6 (spans pillar at E56-57)
  {
    Id: "00kAs00000310054ZZAQ",
    Opportunity_Account_Name: "PCL Construction",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "54.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 6 - Wednesday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-PCL-001",
  },
  {
    Id: "00kAs00000310055ZZAQ",
    Opportunity_Account_Name: "PCL Construction",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "55.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 6 - Wednesday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-PCL-001",
  },
  // Pillar at E56-57
  {
    Id: "00kAs00000310058ZZAQ",
    Opportunity_Account_Name: "PCL Construction",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "58.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 6 - Wednesday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-PCL-001",
  },
  {
    Id: "00kAs00000310059ZZAQ",
    Opportunity_Account_Name: "PCL Construction",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "59.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 6 - Wednesday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-PCL-001",
  },

  // Pembina Pipeline - 6 seats spanning across pillar in Row E (72-77) - Day 9 (spans pillar at E74-75)
  {
    Id: "00kAs00000320072ZZAQ",
    Opportunity_Account_Name: "Pembina Pipeline",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "72.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Pembina-001",
  },
  {
    Id: "00kAs00000320073ZZAQ",
    Opportunity_Account_Name: "Pembina Pipeline",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "73.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Pembina-001",
  },
  // Pillar at E74-75
  {
    Id: "00kAs00000320076ZZAQ",
    Opportunity_Account_Name: "Pembina Pipeline",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "76.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Pembina-001",
  },
  {
    Id: "00kAs00000320077ZZAQ",
    Opportunity_Account_Name: "Pembina Pipeline",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "77.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Pembina-001",
  },

  // Imperial Oil - 8 seats spanning across large pillar in Row E (90-97) - Day 4 (spans pillar at E92-95)
  {
    Id: "00kAs00000330090ZZAQ",
    Opportunity_Account_Name: "Imperial Oil",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "90.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 4 - Monday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-ImperialOil-001",
  },
  {
    Id: "00kAs00000330091ZZAQ",
    Opportunity_Account_Name: "Imperial Oil",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "91.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 4 - Monday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-ImperialOil-001",
  },
  // Pillar at E92-95
  {
    Id: "00kAs00000330096ZZAQ",
    Opportunity_Account_Name: "Imperial Oil",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "96.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 4 - Monday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-ImperialOil-001",
  },
  {
    Id: "00kAs00000330097ZZAQ",
    Opportunity_Account_Name: "Imperial Oil",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "97.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 4 - Monday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-ImperialOil-001",
  },

  // ===== LONGER BOOKINGS (10 SEATS) =====

  // Syncrude - 10 adjacent seats in Row C (68-77) - Day 5
  {
    Id: "00kAs00000340068ZZAQ",
    Opportunity_Account_Name: "Syncrude",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "68.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Syncrude-001",
  },
  {
    Id: "00kAs00000340069ZZAQ",
    Opportunity_Account_Name: "Syncrude",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "69.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Syncrude-001",
  },
  {
    Id: "00kAs00000340070ZZAQ",
    Opportunity_Account_Name: "Syncrude",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "70.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Syncrude-001",
  },
  {
    Id: "00kAs00000340071ZZAQ",
    Opportunity_Account_Name: "Syncrude",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "71.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Syncrude-001",
  },
  {
    Id: "00kAs00000340072ZZAQ",
    Opportunity_Account_Name: "Syncrude",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "72.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Syncrude-001",
  },
  {
    Id: "00kAs00000340073ZZAQ",
    Opportunity_Account_Name: "Syncrude",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "73.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Syncrude-001",
  },
  {
    Id: "00kAs00000340074ZZAQ",
    Opportunity_Account_Name: "Syncrude",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "74.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Syncrude-001",
  },
  {
    Id: "00kAs00000340075ZZAQ",
    Opportunity_Account_Name: "Syncrude",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "75.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Syncrude-001",
  },
  {
    Id: "00kAs00000340076ZZAQ",
    Opportunity_Account_Name: "Syncrude",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "76.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Syncrude-001",
  },
  {
    Id: "00kAs00000340077ZZAQ",
    Opportunity_Account_Name: "Syncrude",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "77.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Syncrude-001",
  },

  // Nutrien - 10 adjacent seats in Row B (86-95) - Day 7
  {
    Id: "00kAs00000350086ZZAQ",
    Opportunity_Account_Name: "Nutrien",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "86.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Nutrien-001",
  },
  {
    Id: "00kAs00000350087ZZAQ",
    Opportunity_Account_Name: "Nutrien",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "87.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Nutrien-001",
  },
  {
    Id: "00kAs00000350088ZZAQ",
    Opportunity_Account_Name: "Nutrien",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "88.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Nutrien-001",
  },
  {
    Id: "00kAs00000350089ZZAQ",
    Opportunity_Account_Name: "Nutrien",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "89.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Nutrien-001",
  },
  {
    Id: "00kAs00000350090ZZAQ",
    Opportunity_Account_Name: "Nutrien",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "90.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Nutrien-001",
  },
  {
    Id: "00kAs00000350091ZZAQ",
    Opportunity_Account_Name: "Nutrien",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "91.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Nutrien-001",
  },
  {
    Id: "00kAs00000350092ZZAQ",
    Opportunity_Account_Name: "Nutrien",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "92.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Nutrien-001",
  },
  {
    Id: "00kAs00000350093ZZAQ",
    Opportunity_Account_Name: "Nutrien",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "93.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Nutrien-001",
  },
  {
    Id: "00kAs00000350094ZZAQ",
    Opportunity_Account_Name: "Nutrien",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "94.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Nutrien-001",
  },
  {
    Id: "00kAs00000350095ZZAQ",
    Opportunity_Account_Name: "Nutrien",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "95.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Nutrien-001",
  },
  // Day 1 - Friday bookings

  // Connected seats: Tech Innovations - 3 adjacent seats in Row A (50-52) - Day 1
  {
    Id: "00kAs00000230050ZZAQ",
    Opportunity_Account_Name: "Tech Innovations",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "50.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TechInnovations-001",
  },
  {
    Id: "00kAs00000230051ZZAQ",
    Opportunity_Account_Name: "Tech Innovations",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "51.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TechInnovations-001",
  },
  {
    Id: "00kAs00000230052ZZAQ",
    Opportunity_Account_Name: "Tech Innovations",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "52.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TechInnovations-001",
  },

  // Connected seats: Mountain Resources - 3 adjacent seats in Row A (53-55) - Day 1 (side by side with Tech Innovations)
  {
    Id: "00kAs00000230053ZZAQ",
    Opportunity_Account_Name: "Mountain Resources",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "53.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-MountainResources-001",
  },
  {
    Id: "00kAs00000230054ZZAQ",
    Opportunity_Account_Name: "Mountain Resources",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "54.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-MountainResources-001",
  },
  {
    Id: "00kAs00000230055ZZAQ",
    Opportunity_Account_Name: "Mountain Resources",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "55.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-MountainResources-001",
  },

  // Connected seats: Calgary Co-op - 4 adjacent seats in Row C (41-44) - Day 1
  {
    Id: "00kAs00000030041ZZAQ",
    Opportunity_Account_Name: "Calgary Co-op",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "41.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-CalgaryCoOp-001",
  },
  {
    Id: "00kAs00000030042ZZAQ",
    Opportunity_Account_Name: "Calgary Co-op",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "42.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-CalgaryCoOp-001",
  },
  {
    Id: "00kAs00000030043ZZAQ",
    Opportunity_Account_Name: "Calgary Co-op",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "43.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-CalgaryCoOp-001",
  },
  {
    Id: "00kAs00000030044ZZAQ",
    Opportunity_Account_Name: "Calgary Co-op",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "44.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-CalgaryCoOp-001",
  },

  // Connected seats: TransCanada Pipeline - Row D seats 35-39 - Day 1
  {
    Id: "00kAs00000060035ZZAQ",
    Opportunity_Account_Name: "TransCanada Pipeline",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "35.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TransCanada-001",
  },
  {
    Id: "00kAs00000060036ZZAQ",
    Opportunity_Account_Name: "TransCanada Pipeline",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "36.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TransCanada-001",
  },
  {
    Id: "00kAs00000060037ZZAQ",
    Opportunity_Account_Name: "TransCanada Pipeline",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "37.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TransCanada-001",
  },
  {
    Id: "00kAs00000060038ZZAQ",
    Opportunity_Account_Name: "TransCanada Pipeline",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "38.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TransCanada-001",
  },
  {
    Id: "00kAs00000060039ZZAQ",
    Opportunity_Account_Name: "TransCanada Pipeline",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "39.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TransCanada-001",
  },

  // Connected seats: Shaw Communications - 3 adjacent seats in Row B (38-40) - Day 1
  {
    Id: "00kAs00000080038ZZAQ",
    Opportunity_Account_Name: "Shaw Communications",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "38.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Shaw-001",
  },
  {
    Id: "00kAs00000080039ZZAQ",
    Opportunity_Account_Name: "Shaw Communications",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "39.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Shaw-001",
  },
  {
    Id: "00kAs00000080040ZZAQ",
    Opportunity_Account_Name: "Shaw Communications",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "40.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 1 - Friday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Shaw-001",
  },

  // Day 2 - Saturday bookings

  // Connected seats: ATCO Gas - 5 adjacent seats in Row B (45-49) - Day 2
  {
    Id: "00kAs00000040045ZZAQ",
    Opportunity_Account_Name: "ATCO Gas",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "45.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-ATCO-001",
  },
  {
    Id: "00kAs00000040046ZZAQ",
    Opportunity_Account_Name: "ATCO Gas",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "46.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-ATCO-001",
  },
  {
    Id: "00kAs00000040047ZZAQ",
    Opportunity_Account_Name: "ATCO Gas",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "47.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-ATCO-001",
  },
  {
    Id: "00kAs00000040048ZZAQ",
    Opportunity_Account_Name: "ATCO Gas",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "48.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-ATCO-001",
  },
  {
    Id: "00kAs00000040049ZZAQ",
    Opportunity_Account_Name: "ATCO Gas",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "49.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-ATCO-001",
  },

  // Connected seats: WestJet Airlines - Row E seats 30-34 - Day 2
  {
    Id: "00kAs00000070030ZZAQ",
    Opportunity_Account_Name: "WestJet Airlines",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "30.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-WestJet-001",
  },
  {
    Id: "00kAs00000070031ZZAQ",
    Opportunity_Account_Name: "WestJet Airlines",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "31.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-WestJet-001",
  },
  {
    Id: "00kAs00000070032ZZAQ",
    Opportunity_Account_Name: "WestJet Airlines",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "32.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-WestJet-001",
  },
  {
    Id: "00kAs00000070033ZZAQ",
    Opportunity_Account_Name: "WestJet Airlines",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "33.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-WestJet-001",
  },
  {
    Id: "00kAs00000070034ZZAQ",
    Opportunity_Account_Name: "WestJet Airlines",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "34.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 2 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-WestJet-001",
  },

  // Day 3 - Sunday bookings

  // Connected seats: Suncor Energy - 6 adjacent seats in Row A (38-43) - Day 3
  {
    Id: "00kAs00000050038ZZAQ",
    Opportunity_Account_Name: "Suncor Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "38.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Suncor-001",
  },
  {
    Id: "00kAs00000050039ZZAQ",
    Opportunity_Account_Name: "Suncor Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "39.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Suncor-001",
  },
  {
    Id: "00kAs00000050040ZZAQ",
    Opportunity_Account_Name: "Suncor Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "40.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Suncor-001",
  },
  {
    Id: "00kAs00000050041ZZAQ",
    Opportunity_Account_Name: "Suncor Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "41.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Suncor-001",
  },
  {
    Id: "00kAs00000050042ZZAQ",
    Opportunity_Account_Name: "Suncor Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "42.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Suncor-001",
  },
  {
    Id: "00kAs00000050043ZZAQ",
    Opportunity_Account_Name: "Suncor Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "43.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 3 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Suncor-001",
  },

  // Day 4 - Monday bookings

  // BMO Financial Group - 4 adjacent seats in Row C (35-38) - Day 4
  {
    Id: "00kAs00000090035ZZAQ",
    Opportunity_Account_Name: "BMO Financial Group",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "35.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 4 - Monday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-BMO-001",
  },
  {
    Id: "00kAs00000090036ZZAQ",
    Opportunity_Account_Name: "BMO Financial Group",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "36.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 4 - Monday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-BMO-001",
  },
  {
    Id: "00kAs00000090037ZZAQ",
    Opportunity_Account_Name: "BMO Financial Group",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "37.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 4 - Monday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-BMO-001",
  },
  {
    Id: "00kAs00000090038ZZAQ",
    Opportunity_Account_Name: "BMO Financial Group",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "38.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 4 - Monday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-BMO-001",
  },

  // Day 5 - Tuesday bookings

  // Connected seats: Deloitte - 3 adjacent seats in Row D (42-44) - Day 5
  {
    Id: "00kAs00000110042ZZAQ",
    Opportunity_Account_Name: "Deloitte",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "42.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Deloitte-001",
  },
  {
    Id: "00kAs00000110043ZZAQ",
    Opportunity_Account_Name: "Deloitte",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "43.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Deloitte-001",
  },
  {
    Id: "00kAs00000110044ZZAQ",
    Opportunity_Account_Name: "Deloitte",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "44.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Deloitte-001",
  },

  // Connected seats: RBC Royal Bank - 5 adjacent seats in Row B (30-34) - Day 5
  {
    Id: "00kAs00000120030ZZAQ",
    Opportunity_Account_Name: "RBC Royal Bank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "30.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-RBC-001",
  },
  {
    Id: "00kAs00000120031ZZAQ",
    Opportunity_Account_Name: "RBC Royal Bank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "31.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-RBC-001",
  },
  {
    Id: "00kAs00000120032ZZAQ",
    Opportunity_Account_Name: "RBC Royal Bank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "32.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-RBC-001",
  },
  {
    Id: "00kAs00000120033ZZAQ",
    Opportunity_Account_Name: "RBC Royal Bank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "33.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-RBC-001",
  },
  {
    Id: "00kAs00000120034ZZAQ",
    Opportunity_Account_Name: "RBC Royal Bank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "34.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 5 - Tuesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-RBC-001",
  },

  // Day 6 - Wednesday bookings

  // Connected seats: Husky Energy - 4 adjacent seats in Row A (46-49) - Day 6
  {
    Id: "00kAs00000130046ZZAQ",
    Opportunity_Account_Name: "Husky Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "46.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 6 - Wednesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Husky-001",
  },
  {
    Id: "00kAs00000130047ZZAQ",
    Opportunity_Account_Name: "Husky Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "47.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 6 - Wednesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Husky-001",
  },
  {
    Id: "00kAs00000130048ZZAQ",
    Opportunity_Account_Name: "Husky Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "48.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 6 - Wednesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Husky-001",
  },
  {
    Id: "00kAs00000130049ZZAQ",
    Opportunity_Account_Name: "Husky Energy",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "49.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 6 - Wednesday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Husky-001",
  },

  // Day 7 - Thursday bookings

  // Connected seats: CP Rail - 6 adjacent seats in Row C (45-50) - Day 7
  {
    Id: "00kAs00000150045ZZAQ",
    Opportunity_Account_Name: "CP Rail",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "45.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CPRail-001",
  },
  {
    Id: "00kAs00000150046ZZAQ",
    Opportunity_Account_Name: "CP Rail",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "46.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CPRail-001",
  },
  {
    Id: "00kAs00000150047ZZAQ",
    Opportunity_Account_Name: "CP Rail",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "47.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CPRail-001",
  },
  {
    Id: "00kAs00000150048ZZAQ",
    Opportunity_Account_Name: "CP Rail",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "48.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CPRail-001",
  },
  {
    Id: "00kAs00000150049ZZAQ",
    Opportunity_Account_Name: "CP Rail",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "49.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CPRail-001",
  },
  {
    Id: "00kAs00000150050ZZAQ",
    Opportunity_Account_Name: "CP Rail",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "50.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 7 - Thursday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CPRail-001",
  },

  // Day 8 - Friday bookings

  // Connected seats: TD Bank - 5 adjacent seats in Row E (40-44) - Day 8
  {
    Id: "00kAs00000170040ZZAQ",
    Opportunity_Account_Name: "TD Bank",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "40.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TDBank-001",
  },
  {
    Id: "00kAs00000170041ZZAQ",
    Opportunity_Account_Name: "TD Bank",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "41.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TDBank-001",
  },
  {
    Id: "00kAs00000170042ZZAQ",
    Opportunity_Account_Name: "TD Bank",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "42.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TDBank-001",
  },
  {
    Id: "00kAs00000170043ZZAQ",
    Opportunity_Account_Name: "TD Bank",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "43.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TDBank-001",
  },
  {
    Id: "00kAs00000170044ZZAQ",
    Opportunity_Account_Name: "TD Bank",
    "PricebookEntry.Product2.Row": "E",
    "PricebookEntry.Product2.Seat_Number": "44.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-TDBank-001",
  },

  // Connected seats: CIBC - 3 adjacent seats in Row D (30-32) - Day 8 Evening Show
  {
    Id: "00kAs00000180030ZZAQ",
    Opportunity_Account_Name: "CIBC",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "30.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CIBC-001",
  },
  {
    Id: "00kAs00000180031ZZAQ",
    Opportunity_Account_Name: "CIBC",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "31.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CIBC-001",
  },
  {
    Id: "00kAs00000180032ZZAQ",
    Opportunity_Account_Name: "CIBC",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "32.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 8 - Friday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-CIBC-001",
  },

  // Day 9 - Saturday bookings

  // Connected seats: Scotiabank - 5 adjacent seats in Row B (35-39) - Day 9
  {
    Id: "00kAs00000190035ZZAQ",
    Opportunity_Account_Name: "Scotiabank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "35.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Scotiabank-001",
  },
  {
    Id: "00kAs00000190036ZZAQ",
    Opportunity_Account_Name: "Scotiabank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "36.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Scotiabank-001",
  },
  {
    Id: "00kAs00000190037ZZAQ",
    Opportunity_Account_Name: "Scotiabank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "37.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Scotiabank-001",
  },
  {
    Id: "00kAs00000190038ZZAQ",
    Opportunity_Account_Name: "Scotiabank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "38.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Scotiabank-001",
  },
  {
    Id: "00kAs00000190039ZZAQ",
    Opportunity_Account_Name: "Scotiabank",
    "PricebookEntry.Product2.Row": "B",
    "PricebookEntry.Product2.Seat_Number": "39.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Scotiabank-001",
  },

  // Connected seats: Enbridge - 4 adjacent seats in Row A (34-37) - Day 9 Rodeo
  {
    Id: "00kAs00000200034ZZAQ",
    Opportunity_Account_Name: "Enbridge",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "34.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Enbridge-001",
  },
  {
    Id: "00kAs00000200035ZZAQ",
    Opportunity_Account_Name: "Enbridge",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "35.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Enbridge-001",
  },
  {
    Id: "00kAs00000200036ZZAQ",
    Opportunity_Account_Name: "Enbridge",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "36.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Enbridge-001",
  },
  {
    Id: "00kAs00000200037ZZAQ",
    Opportunity_Account_Name: "Enbridge",
    "PricebookEntry.Product2.Row": "A",
    "PricebookEntry.Product2.Seat_Number": "37.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 9 - Saturday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Enbridge-001",
  },

  // Day 10 - Sunday bookings

  // Connected seats: Cenovus Energy - 6 adjacent seats in Row C (30-35) - Day 10
  {
    Id: "00kAs00000210030ZZAQ",
    Opportunity_Account_Name: "Cenovus Energy",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "30.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Cenovus-001",
  },
  {
    Id: "00kAs00000210031ZZAQ",
    Opportunity_Account_Name: "Cenovus Energy",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "31.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Cenovus-001",
  },
  {
    Id: "00kAs00000210032ZZAQ",
    Opportunity_Account_Name: "Cenovus Energy",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "32.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Cenovus-001",
  },
  {
    Id: "00kAs00000210033ZZAQ",
    Opportunity_Account_Name: "Cenovus Energy",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "33.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Cenovus-001",
  },
  {
    Id: "00kAs00000210034ZZAQ",
    Opportunity_Account_Name: "Cenovus Energy",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "34.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Cenovus-001",
  },
  {
    Id: "00kAs00000210035ZZAQ",
    Opportunity_Account_Name: "Cenovus Energy",
    "PricebookEntry.Product2.Row": "C",
    "PricebookEntry.Product2.Seat_Number": "35.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Rodeo",
    "Opportunity.Id": "OPP-Cenovus-001",
  },

  // Connected seats: Telus - 4 adjacent seats in Row D (46-49) - Day 10 Evening Show
  {
    Id: "00kAs00000220046ZZAQ",
    Opportunity_Account_Name: "Telus",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "46.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Telus-001",
  },
  {
    Id: "00kAs00000220047ZZAQ",
    Opportunity_Account_Name: "Telus",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "47.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Telus-001",
  },
  {
    Id: "00kAs00000220048ZZAQ",
    Opportunity_Account_Name: "Telus",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "48.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Telus-001",
  },
  {
    Id: "00kAs00000220049ZZAQ",
    Opportunity_Account_Name: "Telus",
    "PricebookEntry.Product2.Row": "D",
    "PricebookEntry.Product2.Seat_Number": "49.0",
    "PricebookEntry.Product2.Day_of_Stampede": "Day 10 - Sunday",
    "PricebookEntry.Product2.Event_Type": "Evening Show",
    "Opportunity.Id": "OPP-Telus-001",
  },
];
